AWSTemplateFormatVersion: '2010-09-09'
Description: VPC with 2 Pub Subnet, 2 Pvt subnet, Gateways, SecurityGroups, 2 Instances, 2 MysqlDB 


Parameters:
  MarketplaceAmiId:
    Type: AWS::EC2::Image::Id
    #Default: ami-0ec4a9b03886a8c5d-- This is for wordpress from aws marketplace
    Default: ami-068c0051b15cdb816 # This is for 
    Description: AMI ID of AmazonLinuxImage

  InstanceType:
    Type: String
    Default: t3.micro

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: wordpress
    Description: EC2 KeyPair name for SSH access

  DBUsername:
    Type: String
    Default: admin
    Description: Master username for MySQL

  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Master password for MySQL

  DBName:
    Type: String
    Default: mysqldb
    Description: Initial database name

  DevDBName:
    Type: String
    Default: devmysqldb
    Description: Initial database name
    
Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: surajVPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MyIGW

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs 'us-east-1']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: wordpress-prod

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs 'us-east-1']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: wordpress-dev

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, and HTTPS
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: InstanceSecurityGroup

  # --------------------
  # Private Subnet
  # --------------------
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PvtSubnet-DB1a

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: us-east-1b
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PvtSubnet-DB1b
  
  # --------------------
  # Elastic IP for NAT
  # --------------------
  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      
  # --------------------
  # NAT Gateway
  # --------------------
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEIP.AllocationId
      SubnetId: !Ref PrivateSubnet1
      Tags:
        - Key: Name
          Value: My-NAT-Gateway


  # --------------------
  # Private Route Table
  # --------------------
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PrivateSubnetRTAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable
      
  PrivateSubnetRTAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable
          
  # --------------------
  # Prod Instance Creation
  # --------------------          
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref MarketplaceAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      #SubnetId: !Ref PublicSubnet1
      #SecurityGroupIds:
      #  - !Ref InstanceSecurityGroup
      NetworkInterfaces:
      - DeviceIndex: 0
        SubnetId: !Ref PublicSubnet1
        AssociatePublicIpAddress: true
        GroupSet:
          - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd mariadb105-server php php-mysqlnd
          sudo systemctl start httpd
          sudo systemctl start mariadb.service
          sudo systemctl start httpd.service
          sudo systemctl start php-fpm.service
          sudo systemctl enable httpd
          sudo echo "<h1>Production - EC2 Instance is running</h1>" > /var/www/html/index.html
          sudo echo "<h1>Hello World from $(hostname -f)</h1>" >> /var/www/html/index.html
      Tags:
        - Key: Name
          Value: wordpress-prod

  # --------------------
  # Dev Instance Creation
  # --------------------      
  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref MarketplaceAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      #SubnetId: !Ref PublicSubnet2
      #SecurityGroupIds:
      #  - !Ref InstanceSecurityGroup
      NetworkInterfaces:
      - DeviceIndex: 0
        SubnetId: !Ref PublicSubnet2
        AssociatePublicIpAddress: true
        GroupSet:
          - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd mariadb105-server php php-mysqlnd
          sudo systemctl start httpd
          sudo systemctl start mariadb.service
          sudo systemctl start httpd.service
          sudo systemctl start php-fpm.service
          sudo systemctl enable httpd
          sudo echo "<h1>Development - EC2 Instance is running</h1>" > /var/www/html/index.html
          sudo echo "<h1>Hello World from $(hostname -f)</h1>" >> /var/www/html/index.html
          sudo hostnamectl set-hostname dev-wordpress
      Tags:
        - Key: Name
          Value: wordpress-dev


  # --------------------
  # Database Security Group
  # --------------------
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow DB access from VPC
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # MySQL / Aurora
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: DB-Security-Group

  # --------------------
  # DB Subnet Group
  # --------------------
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for MySQL
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: prod-db-subnet-group

  # --------------------
  # Productin MySQL RDS Instance
  # --------------------
  MySQLDB1:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: prod-mysql-db
      Engine: mysql
      EngineVersion: "8.0.40"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp2
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup       # DB Security Group ID
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      MultiAZ: false
      BackupRetentionPeriod: 0
      DeletionProtection: false
      AutoMinorVersionUpgrade: true
      Tags:
        - Key: Environment
          Value: Sandbox
        - Key: Name
          Value: prod-mysql-db   
          
  # --------------------
  # Development MySQL RDS Instance
  # --------------------
  MySQLDB2:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: dev-mysql-db
      Engine: mysql
      EngineVersion: "8.0.40"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp2
      DBName: !Ref DevDBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup       # DB Security Group ID
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      MultiAZ: false
      BackupRetentionPeriod: 0
      DeletionProtection: false
      AutoMinorVersionUpgrade: true
      Tags:
        - Key: Environment
          Value: Sandbox
        - Key: Name
          Value: dev-mysql-db
